[package]
name = "floem_vger_renderer"
version.workspace = true
edition = "2021"
repository = "https://github.com/lapce/floem"
description = "A native Rust UI library with fine-grained reactivity"
license.workspace = true

[dependencies]
image = { workspace = true }
resvg = { workspace = true }
peniko = { workspace = true }
wgpu = { workspace = true }

anyhow = "1.0"
# floem-vger-rs = { git = "https://github.com/lapce/vger-rs.git", rev = "3206d47ec1e30b645ddcb0687036ba3e1f0d98ec", version = "0.3.1", package = "floem-vger" }
floem-vger-rs = { path = "D:/vger-rs", package = "floem-vger" }
floem_renderer = { path = "../renderer", version = "0.2.0" }
