[package]
name = "floem_vger_renderer"
version.workspace = true
edition = "2021"
repository = "https://github.com/lapce/floem"
description = "A native Rust UI library with fine-grained reactivity"
license.workspace = true

[dependencies]
image.workspace = true
resvg.workspace = true
raw-window-handle.workspace = true
wgpu.workspace = true

futures = "0.3.26"
anyhow = "1.0.69"
floem-peniko = "0.1.0"
swash = "0.1.8"
# floem-vger-rs = { package = "floem-vger", version = "0.2.7" }  # Alias library to avoid overlap with subcrate
floem-vger-rs = { path = "../../vger-rs" }
floem_renderer = { path = "../renderer", version = "0.1.0" }
