[package]
name = "floem_vger"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
resvg = "0.33.0"
wgpu = "0.17.0"
raw-window-handle = "0.5.1"
futures = "0.3.26"
anyhow = "1.0.69"
peniko = { git = "https://github.com/linebender/peniko", rev = "cafdac9a211a0fb2fec5656bd663d1ac770bcc81" }
swash = "0.1.8"
vger = { git = "https://github.com/lapce/vger-rs", rev = "36cf0cf42e05eeaf94da994549e104968b1f3cd7" }
# vger = { path = "../../vger-rs" }
floem_renderer = { path = "../renderer" }
