[package]
name = "widget-gallery"
version = "0.1.0"
edition = "2021"

[dependencies]
im.workspace = true
floem = { path = "../..", features = ["rfd-async-std", "vello"] }
strum = { version = "0.25.0", features = ["derive"] }
files = { path = "../files/" }

[features]
vello = ["floem/vello"]
