[package]
name = "widget-gallery"
version = "0.1.0"
edition = "2024"

[dependencies]
floem = { path = "../..", features = ["rfd-async-std", "vello"] }
strum = { workspace = true }
files = { path = "../files/", optional = true }
stacks = { path = "../stacks/", optional = true }

[features]
default = ["full"]
vello = ["floem/vello"]
full = ["dep:files", "dep:stacks"]
